### ISSUE TITLE
Add in favicons

### ISSUE THREAD

**Issue by Rhiana** [strategicdata/websurvey.com.au#11]
I just noticed this comment in the default.html

```
<!-- Le fav and touch icons - @todo: fill with your icons or remove -->
```

And realised we don't have any favicons set up for this site. Mine is currently showing the old favicon but I'm not sure what other browsers will do. It also doesn't match our new design.

![screen shot 2015-12-10 at 9 46 46 am](https://cloud.githubusercontent.com/assets/5127756/11701328/00fbd67e-9f23-11e5-89e4-2143799a458a.png)

I've had a go putting one together using a [favicon generator](http://realfavicongenerator.net/) where it generates multiple icons and their links in the HTML across many browsers and devices.
Some could have the "WS" in our colours, otherwise it was white on a WS red background or vis versa

![screen shot 2015-12-09 at 10 04 36 am](https://cloud.githubusercontent.com/assets/5127756/11701265/a304053c-9f22-11e5-9e1a-be8c01c60eec.png)

![screen shot 2015-12-09 at 10 13 23 am](https://cloud.githubusercontent.com/assets/5127756/11701270/a9d2f328-9f22-11e5-896b-cc95c7b1d356.png)
![screen shot 2015-12-09 at 10 13 09 am](https://cloud.githubusercontent.com/assets/5127756/11701272/a9fe7fc0-9f22-11e5-8189-f739957dd58f.png)
![screen shot 2015-12-09 at 10 11 28 am](https://cloud.githubusercontent.com/assets/5127756/11701273/aa189bee-9f22-11e5-9ba4-b0747db56afc.png)
![screen shot 2015-12-09 at 10 11 45 am](https://cloud.githubusercontent.com/assets/5127756/11701274/aa1b41f0-9f22-11e5-8caa-47837485e3c4.png)

Happy to add this in for now or modify it to be something a little different (my design skills are quite limited in this area however). Otherwise should we get a designer to make a new logo then add it in?

**Comment by veryrusty** [comment]
I have a recollection that we were using the Stratdat favicon, which is what the surveys use. eg
`https://demo.websurvey.net.au/favicon.ico`.  I'm not sure if touch icons exist though..

**Comment by Rhiana** [comment]
I'm sure I could put it through the same generator and get touch icons and that if that's the design people wanted to go with.
I noticed it was on our demo survey but wasn't sure if we wanted that one or a separate one for the new site.

**Comment by adamc00** [comment]
See what @michellenSD wants to do.

**Comment by michellenSD** [comment]
I'd completely forgotten about that one @veryrusty - we weren't using it on the old website. I like the idea of having the website consistent with our surveys though, so I vote for using that one.

**Comment by Rhiana** [comment]
Do you have a good link for that image @veryrusty? I tried finding it in our Github pages but couldn't see it. That one is a bit small so turns out quite blurry.
