### ISSUE TITLE
No feedback from contact us page

### ISSUE THREAD

**Issue by Rhiana** [strategicdata/websurvey.com.au#13]
The contact form on the contact us page doesn't appear to be working.

Selecting the "Send Message" button gives no feedback and I am unsure if any emails are actually sent.
It should:
 * Let you know which fields are mandatory
 * Provide an error if any fields are left blank on submission
 * Clear the form and provide a confirmation message when the form is submitted successfully

![screen shot 2016-01-14 at 3 49 29 pm](https://cloud.githubusercontent.com/assets/5127756/12316054/6ad5955c-bad6-11e5-826c-ee4c6de6c8b6.png)

**Comment by Rhiana** [comment]
This looks like a potential explanation/solution [form keep](https://formkeep.com/guides/how-to-make-a-contact-form-in-jekyll)

**Comment by adamc00** [comment]
Just remove it and replace it with a mailto:info@websurvey.com.au. This has several advantages anyway.

1. People tend to have their e-mail address correctly configured in their e-mail client. No typos into the form with this method.
2. People have a record of when and what they have sent.
3. No need to configure any form processing on our side.

**Comment by Rhiana** [comment]
Sure, we already have a mailto link next to it and a tel link with the phone number so people can contact us currently.
I'll remove the contact form to prevent confusion.

**Comment by Rhiana** [comment]
Is there any content we want to add now though as it looks a little bare without it?

![screen shot 2016-01-14 at 4 39 39 pm](https://cloud.githubusercontent.com/assets/5127756/12316671/8bf53664-badd-11e5-8a1a-abcb55adcfcd.png)

**Comment by Rhiana** [comment]
Maybe we could redesign it a little like this example below? I think this fits with the styling of the other pages with the large round logos. Could be horizontal like this example and our home page, otherwise I could make it vertical like out features and other pages.

![contact-us-built-by-buffalo-web-design-brighton-uk-20130108](https://cloud.githubusercontent.com/assets/5127756/12340504/5cb51454-bb6f-11e5-8d55-1f071bcfc245.jpg)

**Comment by Rhiana** [comment]
I have restyled this page as described above. Here is is on PC, table and mobile view.
The icons and headings are links where applicable.

Let me know if any further styling or content changes are required for this page.

**Desktop**
![screen shot 2016-01-15 at 11 46 29 am](https://cloud.githubusercontent.com/assets/5127756/12342373/e964ca08-bb7d-11e5-8846-7da983740be3.png)

**Tablet**
![screen shot 2016-01-15 at 11 46 48 am](https://cloud.githubusercontent.com/assets/5127756/12342374/f40d8328-bb7d-11e5-8f77-4b6464ad06a2.png)

**Mobile**
![screen shot 2016-01-15 at 11 47 28 am](https://cloud.githubusercontent.com/assets/5127756/12342384/080a2458-bb7e-11e5-8bf0-a1be4b8e3938.png)
![screen shot 2016-01-15 at 11 47 37 am](https://cloud.githubusercontent.com/assets/5127756/12342387/0c26dfc2-bb7e-11e5-8921-5979626f7bad.png)

**Comment by adamc00** [comment]
:+1:
