### ISSUE TITLE
Accessibility - Clients

### ISSUE THREAD

**Issue by Rhiana** [strategicdata/websurvey.com.au#2]
The clients carousel have the images as links but they currently re-direct to the home page instead of going to the clients website. 
Do we want the link to go to their website or should I remove the links and have them as static images?
On further inspection a couple of other issues came up that I will need a hand with:

 * Our first client in the list is Towers Perrin who closed in 2010, do we still keep this here?
 * I had trouble with HRC as well, what company is this?

![screen shot 2015-11-27 at 3 24 47 pm](https://cloud.githubusercontent.com/assets/5127756/11434103/4180e174-951b-11e5-81b1-334c6a7bce3a.png)

 * The following pages of the carousel I had trouble finding where in the codebase they are to alter them
 * University of Melbourne has a new logo
![screen shot 2015-11-27 at 3 26 45 pm](https://cloud.githubusercontent.com/assets/5127756/11434106/5db30804-951b-11e5-89bf-5acd2200ccb8.png)

![screen shot 2015-11-27 at 3 27 01 pm](https://cloud.githubusercontent.com/assets/5127756/11434107/62059872-951b-11e5-8a39-756dc45065b2.png)

Looking at the list perhaps it would also be good to revisit which clients are displayed (are there new ones we can add in?) and in what order they are displayed in as NAB for example is very big and towards the end.

**Comment by Rhiana** [comment]
I've had a little look and it turns out making a [carousel accessible](http://www.w3.org/WAI/tutorials/carousels/) is potentially a big task as it looks like no-one does it particularly well and there isn't an out of the box solution. I would potentially have to find a new plugin and customise it to make it accessible.

Is it worth then maybe looking into some [alternatives to carousels](http://www.mightybytes.com/blog/5-alternatives-using-carousel-website-homepage/)? From a UX point of view they aren't very effective. We could have them all showing by default in a grid, something like this? (but with a little more care lining up logos etc)

![client list grid](https://cloud.githubusercontent.com/assets/5127756/11519603/a91e20f8-98ef-11e5-8be9-47f4ad2fd3f7.png)

Another alternative is having an overflow pattern like the characters section in [disney](http://www.disney.com.au/) So you can see some in a grid then trigger more using a button. 

![screen shot 2015-12-02 at 12 27 06 pm](https://cloud.githubusercontent.com/assets/5127756/11519674/266ed2aa-98f0-11e5-86f5-7ed9c60d7f37.png)
It's also quite responsive for mobile view.
![screen shot 2015-12-02 at 12 27 15 pm](https://cloud.githubusercontent.com/assets/5127756/11519680/35624d00-98f0-11e5-83a8-7036e76e52bb.png)

**Comment by michellenSD** [comment]
I like the idea of having them in a grid, rather than having a 'show more'.  Also, HRC is the Health Research Council of New Zealand

**Comment by Rhiana** [comment]
Thanks @michellenSD 
I have actually found an [accessible carousel](http://benschwarz.github.io/gallery-css/). It runs off pure CSS no javascript library needed and the controls are links so usable with the keyboard.
Here's how it looks so far but it's all customisable so happy to change the look and feel.

![screen shot 2015-12-02 at 3 55 07 pm](https://cloud.githubusercontent.com/assets/5127756/11522624/3d2f13de-990d-11e5-83eb-6042cc07fbf4.png)
