### ISSUE TITLE
Accessibility - Unique titles

### ISSUE THREAD

**Issue by Rhiana** [strategicdata/websurvey.com.au#3]
Currently the title for the website is static as "WebSurvey - Home"

This would be improved by having a unique title per page so "WebSurvey - Services" etc

Unfortunately I am not familiar enough with the project/language to set this up, if someone could help me out or point me in the right direction that would be great.

![screen shot 2015-11-27 at 4 00 47 pm](https://cloud.githubusercontent.com/assets/5127756/11434412/19501094-9520-11e5-8ad1-f0f09dbf8ed2.png)

**Comment by adamc00** [comment]
It's also better to go the other way e.g. "Home - Websurvey", "Services - Websurvey", that way the unique bit is easily visible even when some parts get cut off. Browser history is a good example, you see the specific label first, then the site name.

**Comment by Rhiana** [comment]
No worries I see what you mean, I'm just not sure how to do it...

**Comment by adamc00** [comment]
They come from the title element of the head section. Is that what you mean?

**Comment by Rhiana** [comment]
Not really, I can see it hard coded in the [default.html](https://github.com/strategicdata/websurvey.com.au/blob/master/_layouts/default.html)

``` 
<title>WebSurvey - Home</title>
```

I'm thinking we'll have to make some sort of variable(?) to add in there to change for each page like

```
<title> {{ page.title }} - WebSurvey</title>
```

But I'm not familiar enough with this set up to figure out that part

**Comment by veryrusty** [comment]
@Rhiana that title markup looks correct. If Jeklly doesn't automatically provide a page.title, you'll need to add the variable to the yaml front-matter for each page.

**Comment by Rhiana** [comment]
@veryrusty wow I just guessed that markup, thanks for the tips I'll give that a go and see if I can get it to work.

**Comment by Rhiana** [comment]
Addressed in this [commit](https://github.com/strategicdata/websurvey.com.au/commit/3fc248fbf3eb27d5ea6e8d2451710b3ec14665b1). I have updated the code in the default html as above then added in yaml at the top of each page for the title as below.

```
---
title: About
---
```
