### ISSUE TITLE
Upgrade to SASS

### ISSUE THREAD

**Issue by Rhiana** [strategicdata/websurvey.com.au#8]
At the moment there are a lot of different stylesheets competing with each other making it difficult and time consuming to make changes.

It looks like [Jekyll](http://jekyllrb.com/docs/assets/) has some SASS compilers built in so it should be easy enough to upgrade to scss and tidy up the styling a a little. This will make it easier to read and maintain. It will also make the styling more consistent cross browser.

It will also reduce the number of css files that need to be loaded increasing performance. At the moment I count at least 10 css files, some minified some not.

**Comment by adamc00** [comment]
Go for it @Rhiana. Ash or Steve should be able to assist if you get stuck on anything.
